title: Machine Learning
description: Intro to Machine Learning
template:
  repo: machine-learning-template
  name: machine-learning
  description: repo that hosts data and code for the "Intro to ML" course
preferences:
- type: radio
  name: gitTool
  label: Preferred Git tool
  description: Learn right from the web UI, or using your chosen tool
  options:
  - label: Use the GitHub.com web interface
    value: dotcom
  - label: Use the command line
    value: cli
  - label: Use Visual Studio Code
    value: vscode
- type: dropdown
  name: language
  label: Language
  description: Choose your preferred language.
  options:
  - label: English
    value: en
  - label: Español
    value: es
  - label: 日本語
    value: ja
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  
- title: Assign yourself
  description: Assign the first issue to yourself.
  translations:
    es:
      title: Asígnate
      description: Asígnate la primera propuesta. 
    ja:
      title: 担当者になろう
      description: 初めてのイシューの担当者になりましょう。
  event: issues.assigned
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    left: '%payload.assignee.login%'
    operator: ===
    right: '%user.username%'
  - type: respond
    with: turn-on-gh-pages.md
